### ISSUE TITLE
Docker HTTPS-Portal and Sismics

### ISSUE THREAD

**Issue by petrk94** [sismics/docs#251]
Hello,

Im currently again facing the problem with HTTPS in docker, while I found a solution with [HTTPS-Portal](https://github.com/SteveLTN/https-portal), I get a problem, what I dont know how to solve in Sismics configuration.

I have started HTTPS-Portal and Sismics over a dockerfile and it work well, https and ssl is working, BUT Sismics, is adding there the http which cause problems.

After opening the subdomain, I get forwarded to this URL:
`https://http//MYIP:8080/`
so its trying to open the host "http", but this doesnt make sense, thats inside the configuration of sismics and I dont know how to remove this.

This is my dockerfile, which base on this https://github.com/SteveLTN/https-portal#quick-start

```
https-portal:
  image: steveltn/https-portal:1
  ports:
    - '80:80'
    - '443:443'
  links:
    - sismics
  environment:
    DOMAINS: 'sub.domain.net => sub.domain.net:80'
    STAGE: 'production'

sismics:
  image: sismics/docs
```

As it run, it produce this log

```
sismics_1       | 26 Oct 2018 18:52:06,866 INFO com.sismics.docs.core.service.FileService.startUp(FileService.java:39) File service starting up
sismics_1       | 26 Oct 2018 18:52:06,879 INFO com.sismics.docs.core.service.InboxService.startUp(InboxService.java:49) Inbox service starting up
sismics_1       | 2018-10-26 18:52:09.529:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@4dfa3a9d{/,file:///tmp/jetty-0.0.0.0-8080-docs.war-_-any-5821378666533670531.dir/webapp/,AVAILABLE}{/docs.war}
sismics_1       | 2018-10-26 18:52:09.560:INFO:oejs.AbstractConnector:main: Started ServerConnector@26ee56fa{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
sismics_1       | 2018-10-26 18:52:09.561:INFO:oejs.Server:main: Started @13016ms

```

What mean, that the port 8080 get used, but out of the config, so please tell me how to change it in the dockerfile so it will work.
Thanks
