### ISSUE TITLE
Docker-compose file for first run

### ISSUE THREAD

**Issue by petrk94** [sismics/docs#261]
Hello,

I have the open question in https://github.com/sismics/docs/issues/251#issuecomment-437571280
I would like to see a functional docker-compose file, due the problem in #251 cant be solved without it

**Comment by jendib** [comment]
Sorry it's still a pure Docker issue, not related to Docs

**Comment by petrk94** [comment]
@jendib 
Therefore I would like to see some more help, especially to solve a problem, which is caused due not right documentation.
I just looked for how a sismics/docs docker-compose.yml file would look like to work properly.
HTTPS-Portal developer was very helpful and has provided me after investigating sismics/doc corretly docker-compose file

```
version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - sismics
    environment:
      DOMAINS: local.steveltn.me -> http://sismics:8080
      STAGE: 'local'

  sismics:
      image: sismics/docs
      ports:
          - "8100:8080"
      environment:
          - DOCS_BASE_URL='http://[your-docker-host-ip]:8100'
      volumes:
          - sismics_docs_latest/data

```
