### ISSUE TITLE
OCR issue with accented characters

### ISSUE THREAD

**Issue by touste** [sismics/docs#314]
Hi, I've been having a problem with documents containing accented characters. For example, the sample document in French from [this dataset](https://www.ocrsdk.com/documentation/sample-images/) gives the following output:

> AntiquitÃ©
> 
> On peut appeler Â« papier Â»
> tout ce qui est constituÃ© de
> fibres de celluloses en
> majoritÃ©, donc dâ€™origine
> vÃ©gÃ©tale, mises en
> suspension dans de lâ€™eau
> puis Ã©gouttÃ©es sur une
> surface plane. Quel que
> soit le procÃ©dÃ© employÃ©,
> que ce soit propre ou sale,
> fin ou grossier, quâ€™il nâ€™y ait
> que de la cellulose ou
> dâ€™autres matiÃ¨res ajoutÃ©es
> (laine, soie..â€¦.), câ€™est la
> mise en suspension dans
> lâ€™eau des fibres et leur
> Ã©gouttage qui permettent
> de constituer le papier.
> 
> ...

At first glance it looks like a character encoding issue. Note that I've correctly configured French as the language for this document. 

I'm running the latest release (v 1.6) in Docker with the following docker-compose.yml:
```

version: '3'
services:

  teedy:
    image: sismics/docs:latest
    container_name: teedy
    environment:
      - DOCS_BASE_URL=https://*******
    volumes:
      - /DATA/appdata/sismics:/data
    networks:
      - traefik_net
      - internal_net
    restart: unless-stopped
    labels:
      - 'traefik.backend=sismics'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:*******'
      - 'traefik.enable=true'

  importer:
    image: mediadepot/sismics-importer
    container_name: teedy-importer
    environment:
      - PUID=1000
      - PGID=100
      - SISMICS_BASE_URL=http://teedy:8080
      - SISMICS_USERNAME=*******
      - SISMICS_PASSWORD=*******
    volumes:
      - /DATA/SMB/Scanner/watchfolder:/watch
    networks:
      - internal_net
    restart: unless-stopped

networks:
  traefik_net:
    external: true
  internal_net:
    external: false
```

I don't see anything interesting in the logs that could explain this behaviour:
```
08 Apr 2019 11:11:15,279 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:52) File created event: FileCreatedAsyncEvent{file=File{id=b5812890-0ead-4cef-a333-840a77bdb7ca, name=MobIMG_0124.jpg}, language=null} 


08 Apr 2019 11:11:18,097 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.processFile(FileProcessingAsyncListener.java:147) File content extracted in 0ms 


08 Apr 2019 11:11:19,583 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.processFile(FileProcessingAsyncListener.java:147) File content extracted in 1ms 


Apr 08, 2019 11:11:59 AM org.glassfish.jersey.servlet.WebComponent filterFormParameters


WARNING: A servlet request to the URI http://****/api/document?language=fra&title=test2 contains form parameters in the request body but the request body has been consumed by the servlet or a servlet filter accessing the request parameters. Only resource methods using @FormParam will work as expected. Resource methods consuming the request body by other means will not work as expected.


08 Apr 2019 11:11:59,423 INFO com.sismics.docs.core.listener.async.DocumentCreatedAsyncListener.on(DocumentCreatedAsyncListener.java:33) Document created event: DocumentCreatedAsyncEvent{document=Document{id=4379836a-e29f-4fe6-8ed4-111b255ff5cc}} 


08 Apr 2019 11:11:59,535 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:75) File updated event: FileUpdatedAsyncEvent{file=File{id=02129eea-52c1-4a28-b169-132b89d6ef4c, name=[Untitled]001.jpg}, language=fra} 


08 Apr 2019 11:11:59,549 INFO com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:39) Document updated event: DocumentUpdatedAsyncEvent{documentId=4379836a-e29f-4fe6-8ed4-111b255ff5cc} 




019 11:11:59,611 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.on(FileProcessingAsyncListener.java:75) File updated event: FileUpdatedAsyncEvent{file=File{id=b5812890-0ead-4cef-a333-840a77bdb7ca, name=MobIMG_0124.jpg}, language=fra} 


08 Apr 2019 11:11:59,612 INFO com.sismics.docs.core.listener.async.DocumentUpdatedAsyncListener.on(DocumentUpdatedAsyncListener.java:39) Document updated event: DocumentUpdatedAsyncEvent{documentId=4379836a-e29f-4fe6-8ed4-111b255ff5cc} 


08 Apr 2019 11:12:29,154 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.processFile(FileProcessingAsyncListener.java:147) File content extracted in 25,320ms 


08 Apr 2019 11:12:29,882 INFO com.sismics.docs.core.listener.async.FileProcessingAsyncListener.processFile(FileProcessingAsyncListener.java:147) File content extracted in 28,463ms 
```

Thanks!
