### ISSUE TITLE
Blank preview popup

### ISSUE THREAD

**Issue by junpet** [sismics/docs#363]
I just installed `docs` using Docker. I've to search for a little bit to use with PostgreSQL, but I could manage it. Please improve this section in the `readme.md`. Thanks.

Anyway, my `docker-compose.yml` can be found at the bottom. As you can see I'm using `traefik`. I can connect, log in, upload `.pdf` files, but when I click on one of the preview I got a blank (transparent) [popup](https://user-images.githubusercontent.com/3465278/71540536-492a8c80-294c-11ea-97ee-89b34daa0f4a.png). Well, the `.pdf` is downloaded after clicking the preview. As it mentioned, I set the environment variable `DOCS_BASE_URL`. What am I missing?

Hint: My main browser is the latest Firefox. I've tried with the latest Vivaldi as well, and I got the following text in the [popup](https://user-images.githubusercontent.com/3465278/71540701-46309b80-294e-11ea-96bc-ce5143cc9e97.png): 
```docs.[my domain, but I don't want to share] refused to connect.```
I force `https` instead of `http` with `traefik`. I think `docs` want to show the preview with `http` instead of `https`, and that's why the connection is refused. But this is an amateur guess from me.

Could you help me?

```yml
version: "3.7"

services:
  docs:
    image: sismics/docs:v1.7
    container_name: docs
    restart: always
    environment:
      - DOCS_BASE_URL=https://docs.${DOMAINNAME}
      - DATABASE_URL=jdbc:postgresql://db:5432/docs
      - DATABASE_USER=docs
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - docs-data:/data
    networks:
      - traefik-network
      - postgres-network
    labels:
      - "traefik.enable=true"
      - "traefik.backend=docs"
      - "traefik.frontend.rule=Host:docs.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik-network"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

volumes:
  docs-data:
    driver: local-persist
    driver_opts:
      mountpoint: "${DOCKER_VOLUMES}/docs"

networks:
  traefik-network:
    external: true
  postgres-network:
    external: true
```
