### ISSUE TITLE
Username or password incorrect when running importer

### ISSUE THREAD

**Issue by robov** [sismics/docs#436]
When I try to run the importer with the docker-compose I get the following error. 

```
teedy_import    | Environment variables replaced
teedy_import    | Teedy Importer 1.8, https://teedy.io
teedy_import    | 
teedy_import    | This program let you import files from your system to Teedy
teedy_import    | 
teedy_import    | Starting in quiet mode with the following configuration:
teedy_import    | Base URL: http://localhost:8222
teedy_import    | Username: admin
teedy_import    | Password: ***********
teedy_import    | Tag: ab561c2f-37b1-444e-b361-6af54ea54678
teedy_import    | Add tags given #: false
teedy_import    | Language: eng
teedy_import    | Daemon mode: true
teedy_import    | Copy folder: 
teedy_import    | File filter: 
teedy_import    | 
teedy_import    | Username or password incorrect
```
my docker-compose

```
version: "3"

services:
  teedy_import:
    image: sismics/docs-importer:latest
    container_name: teedy_import
    environment:
      TEEDY_TAG: "ab561c2f-37b1-444e-b361-6af54ea54678"
      TEEDY_ADDTAGS: "false"
      TEEDY_LANG: "eng"
      TEEDY_URL: "localhost:8222"
      TEEDY_USERNAME: "admin"
      TEEDY_PASSWORD: "admin"
    volumes:
      - /teedy/watch:/import
```

When I run the linux binaries the importer works and created the following preferences
```
daemon: true
baseUrl: 'http://localhost:8222'
username: admin
password: admin
path: /teedy/watch
tag: ab561c2f-37b1-444e-b361-6af54ea54678
```

What am I missing, why is my docker-compose giving a wrong username/password
