### ISSUE TITLE
default admin credentials documentation not working

### ISSUE THREAD

**Issue by dmccormackmxtr** [sismics/docs#506]
Hello,

Using the default yaml (either) defined in the docs, I am unable to login with a login of admin@example.com and a password of superSecure

`yaml
version: '3'
services:
# Teedy Application
  teedy-server:
    image: sismics/docs:v1.8
    restart: unless-stopped
    ports:
      # Map internal port to host
      - 8080:8080
    environment:
      # Base url to be used
      DOCS_BASE_URL: "https://docs.example.com"
      # Set the admin email
      DOCS_ADMIN_EMAIL_INIT: "admin@example.com"
      # Set the admin password (in this example: "superSecure")
      DOCS_ADMIN_PASSWORD_INIT: "$$2a$$05$$PcMNUbJvsk7QHFSfEIDaIOjk1VI9/E7IPjTKx.jkjPxkx2EOKSoPS"
    volumes:
      - ./docs/data:/data
`

**Comment by jendib** [comment]
DOCS_ADMIN_EMAIL_INIT doesn't define the login, it defines the email of the admin account.

**Comment by dmccormackmxtr** [comment]
I am a bit confused on how I define the default login then, or what it is in the context of that Dockerfile.

**Comment by jendib** [comment]
The default admin login is not configurable, it's always "admin". However you can always make new admin accounts if needed.

**Comment by dmccormackmxtr** [comment]
@jendib ok thanks, apologies if I am doing something silly but I have checked this a bunch and read thru the defaults stored in code (admin,admin) and I still am getting this:

![image](https://user-images.githubusercontent.com/69517452/105217397-ce697c00-5b21-11eb-8d5c-50878d7ee2ab.png)

**Comment by jendib** [comment]
If your server was started the first time using "DOCS_ADMIN_PASSWORD_INIT" then the default admin password is not "admin" anymore, it has been updated.

**Comment by piraterx** [comment]
I am having same issue:
Initially I changed email and password to what I wanted but none of them worked. So I ran new file exactly same as your without making any changes. I am getting same issue. 

Here is what I used in portainer to run container:

```
version: '3'
services:
# Teedy Application
  teedy-server:
    image: sismics/docs:v1.9
    restart: unless-stopped
    ports:
      # Map internal port to host
      - 7860:8080
    environment:
      # Base url to be used
      DOCS_BASE_URL: "https://docs.example.com"
      # Set the admin email
      DOCS_ADMIN_EMAIL_INIT: "admin@example.com"
      # Set the admin password (in this example: "superSecure")
      DOCS_ADMIN_PASSWORD_INIT: "$$2a$$05$$PcMNUbJvsk7QHFSfEIDaIOjk1VI9/E7IPjTKx.jkjPxkx2EOKSoPS"
    volumes:
      - /home/bull/teedy:/data   ----- I changed this only to mount where I wanted to keep data.
```
