### ISSUE TITLE
Unable to Login for a specific user

### ISSUE THREAD

**Issue by aroraakshay999** [sismics/docs#547]
Hi Everyone , 
I am getting below error when i am trying to login for a specific user, 
Rest all Users are working fine.
I am running Teedy with Internal DB (H2)
```2021-06-09 09:42:51 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Timeout trying to lock table ; SQL statement:
delete from T_AUTHENTICATION_TOKEN AS ato  where ato.AUT_IDUSER_C = ? and ato.AUT_LONGLASTED_B = ? and ato.AUT_LASTCONNECTIONDATE_D < ?  [50200-197]
```

**Comment by kylepauljohnson** [comment]
I am having this issue as well with my primary user account which unfortunately is the user with access to everything for the most part in. So I am unable to access all docs at this point. I have one other user for the bulk uploader tool and that login works fine but that user really only has write permissions.

I have attempted to do password resets, however I am seeing similar results there to #559 

Here's logs from the container when I attempt to login. 

```Caused by: org.h2.jdbc.JdbcSQLException: Row {1} not found in primary index "PUBLIC.T_AUTHENTICATION_TOKEN_DATA: 166" [90143-197]
Caused by: org.h2.jdbc.JdbcSQLException: Timeout trying to lock table ; SQL statement:
delete from T_AUTHENTICATION_TOKEN AS ato  where ato.AUT_IDUSER_C = ? and ato.AUT_LONGLASTED_B = ? and ato.AUT_LASTCONNECTIONDATE_D < ?  [50200-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.command.Command.filterConcurrentUpdate(Command.java:316)
	at org.h2.command.Command.executeUpdate(Command.java:268)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:384)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
```

**Comment by jendib** [comment]
Did you try to restart? Your DB seems corrupted, maybe a hard shutdown or something similar.

**Comment by kylepauljohnson** [comment]
@jendib In my case its using the internal I presume SQLlite db. The container, docker, and Synology have all been rebooted at various times since this issue began.

**Comment by stefanpartheym** [comment]
I have the exact same issue unfortunately. I can well image my database (also internal H2 DB) is corrupted. The question is, how could I fix this.
I already tried logging in with my admin user – which fortunately works – and set a new password for the user I want to log in with. However, this does not fix the problem :(

**Comment by jendib** [comment]
@stefanpartheym H2 doesn't support multiple connections so your best bet would be to stop the container and open the .db file (in the volume) directly using a tool like DBeaver.

**Comment by stefanpartheym** [comment]
Hi @jendib, thanks for your hint. I just did as you said:
I copied the `docs.mv.db` file from my server to my local machine in order to be able to view and edit it with DBeaver.
The table `T_AUTHENTICATION_TOKEN` only contained records for my admin user – which is weird, as I thought there must be some sort of a dead record for my actual user.
Anyways, I ended up deleting the whole `T_AUTHENTICATION_TOKEN` table, as records kept showing up in DBeaver after deleting them (even after clicking the "save" button).
I uploaded the DB file back on to my server in the correct directory of the docker volume and started the container again.
However, the result is still the same. I keep getting this error:
```
Timeout trying to lock table {0}; SQL statement: delete from T_AUTHENTICATION_TOKEN AS ato where ato.AUT_IDUSER_C = ? and ato.AUT_LONGLASTED_B = ? and ato.AUT_LASTCONNECTIONDATE_D < ? [50200-199]
```

I'm thinking about creating a new user and reassigning the documents to the new one. But honestly I'm not sure if that works :grimacing:

**Comment by stefanpartheym** [comment]
Ok, I actually managed to migrate from H2 to Postgres and it actually works.
Basically what I did is the following:
- Export data from all tables in the H2 DB into CSV files with DBeaver
- Setup a docker-compose stack with Teedy instance, a Postgres instance and a pgAdmin4 instance
- Import the data from the previously dumped CSV files into the Postgres instance in the docker stack
- => Done, you can now copy around the DB data of the Postgres instance and use it in your production environment.

# Detailed steps

## Export data from all tables in the H2 DB into CSV files with DBeaver

Execute the following SQL-Script in DBeaver while being "connected" to the H2 DB file `docs.mv.db`:
```sql
CALL CSVWRITE('/some/path/db_migrate/sql/T_ACL', 'SELECT * FROM T_ACL');
CALL CSVWRITE('/some/path/db_migrate/sql/T_AUDIT_LOG', 'SELECT * FROM T_AUDIT_LOG');
CALL CSVWRITE('/some/path/db_migrate/sql/T_AUTHENTICATION_TOKEN', 'SELECT * FROM T_AUTHENTICATION_TOKEN');
CALL CSVWRITE('/some/path/db_migrate/sql/T_BASE_FUNCTION', 'SELECT * FROM T_BASE_FUNCTION');
CALL CSVWRITE('/some/path/db_migrate/sql/T_COMMENT', 'SELECT * FROM T_COMMENT');
CALL CSVWRITE('/some/path/db_migrate/sql/T_CONFIG', 'SELECT * FROM T_CONFIG');
CALL CSVWRITE('/some/path/db_migrate/sql/T_CONTRIBUTOR', 'SELECT * FROM T_CONTRIBUTOR');
CALL CSVWRITE('/some/path/db_migrate/sql/T_DOCUMENT', 'SELECT * FROM T_DOCUMENT');
CALL CSVWRITE('/some/path/db_migrate/sql/T_DOCUMENT_METADATA', 'SELECT * FROM T_DOCUMENT_METADATA');
CALL CSVWRITE('/some/path/db_migrate/sql/T_DOCUMENT_TAG', 'SELECT * FROM T_DOCUMENT_TAG');
CALL CSVWRITE('/some/path/db_migrate/sql/T_FILE', 'SELECT * FROM T_FILE');
CALL CSVWRITE('/some/path/db_migrate/sql/T_GROUP', 'SELECT * FROM T_GROUP');
CALL CSVWRITE('/some/path/db_migrate/sql/T_METADATA', 'SELECT * FROM T_METADATA');
CALL CSVWRITE('/some/path/db_migrate/sql/T_PASSWORD_RECOVERY', 'SELECT * FROM T_PASSWORD_RECOVERY');
CALL CSVWRITE('/some/path/db_migrate/sql/T_RELATION', 'SELECT * FROM T_RELATION');
CALL CSVWRITE('/some/path/db_migrate/sql/T_ROLE', 'SELECT * FROM T_ROLE');
CALL CSVWRITE('/some/path/db_migrate/sql/T_ROLE_BASE_FUNCTION', 'SELECT * FROM T_ROLE_BASE_FUNCTION');
CALL CSVWRITE('/some/path/db_migrate/sql/T_ROUTE', 'SELECT * FROM T_ROUTE');
CALL CSVWRITE('/some/path/db_migrate/sql/T_ROUTE_MODEL', 'SELECT * FROM T_ROUTE_MODEL');
CALL CSVWRITE('/some/path/db_migrate/sql/T_ROUTE_STEP', 'SELECT * FROM T_ROUTE_STEP');
CALL CSVWRITE('/some/path/db_migrate/sql/T_SHARE', 'SELECT * FROM T_SHARE');
CALL CSVWRITE('/some/path/db_migrate/sql/T_TAG', 'SELECT * FROM T_TAG');
CALL CSVWRITE('/some/path/db_migrate/sql/T_USER', 'SELECT * FROM T_USER');
CALL CSVWRITE('/some/path/db_migrate/sql/T_USER_GROUP', 'SELECT * FROM T_USER_GROUP');
CALL CSVWRITE('/some/path/db_migrate/sql/T_VOCABULARY', 'SELECT * FROM T_VOCABULARY');
CALL CSVWRITE('/some/path/db_migrate/sql/T_WEBHOOK', 'SELECT * FROM T_WEBHOOK');
```

## Setup a docker-compose stack with Teedy instance, a Postgres instance and a pgAdmin4 instance

I used the following `docker-compose.yaml` file (make sure you tweak user, password and database name to your needs):

```yaml
version: '3'
services:
# Teedy Application
  teedy-server:
    image: sismics/docs:v1.10
    restart: unless-stopped
    ports:
      # Map internal port to host
      - 8080:8080
    environment:
      # Base url to be used
      DOCS_BASE_URL: "http://localhost:8080"
      # Set the admin email
      DOCS_ADMIN_EMAIL_INIT: "admin@example.com"
      # Set the admin password (in this example: "superSecure")
      DOCS_ADMIN_PASSWORD_INIT: "$$2a$$05$$PcMNUbJvsk7QHFSfEIDaIOjk1VI9/E7IPjTKx.jkjPxkx2EOKSoPS"
      # Setup the database connection. "teedy-db" is the hostname
      # and "teedy" is the name of the database the application
      # will connect to.
      DATABASE_URL: "jdbc:postgresql://teedy-db:5432/teedy"
      DATABASE_USER: "teedy_db_user"
      DATABASE_PASSWORD: "teedy_db_password"
    volumes:
      - ./docs/data:/data
    networks:
      - internet
    depends_on:
      - teedy-db

# DB for Teedy
  teedy-db:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "teedy_db_user"
      POSTGRES_PASSWORD: "teedy_db_password"
      POSTGRES_DB: "teedy"
    volumes:
      - ./docs/db:/var/lib/postgresql/data
    networks:
      - internet

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8081:80
    networks:
      - internet
    volumes:
      - ./sql:/scripts
    environment:
      PGADMIN_DEFAULT_EMAIL: default@email.tld
      PGADMIN_DEFAULT_PASSWORD: default_password

networks:
  internet:
    driver: bridge
```

## Import the data from the previously dumped CSV files into the Postgres instance in the docker stack

This step is done by the following – pretty ugly – script (it is expected to be run in directory `/some/path/db_migrate`):

```bash
#!/bin/bash

psqlexec() {
    # Tweak credentials and DB name if necessary
    PGPASSWORD=teedy_db_password psql -U teedy_db_user -h localhost -p 5432 teedy -c "$1"
}

delete() {
    psqlexec "ALTER TABLE $1 DISABLE TRIGGER ALL; DELETE FROM $1; ALTER TABLE $1 ENABLE TRIGGER ALL;"
}

import() {
    psqlexec "ALTER TABLE $1 DISABLE TRIGGER ALL;"
    psqlexec "\\copy $1 from './sql/${1}' CSV HEADER;"
    psqlexec "ALTER TABLE $1 ENABLE TRIGGER ALL;"
}

delete_all() {
    for table in `ls sql`; do
        echo "# delete: $table"
        delete $table
    done
}

import_all() {
    for table in `ls sql`; do
        echo "# import: $table"
        import $table
    done
}

delete_all
import_all
```

## Done

This worked for me at least. Hope I was able to help with this ugly piece of documentation.

Best regards
Stefan
