### ISSUE TITLE
import does not add file

### ISSUE THREAD

**Issue by brightdroid** [sismics/docs#550]
I'll try to add files from a folder with docker, but the importer only creates empty documents (no files added).
And he does it every find interval (30sec.) for the same file.

Interestingly the same file works sometimes, I'v no clue when and why it works sometimes. (99% of the time it does not add the file to the created document)

Docker command I am using:
```bash
docker run --name teedy-import --rm -e TEEDY_TAG=3360dfe1-e24e-4c92-bc3e-41825f20f8de -e TEEDY_ADDTAGS=true -e TEEDY_LANG=deu -e TEEDY_URL='http://x.x.x.x:8088' -e TEEDY_USERNAME=admin -e TEEDY_PASSWORD=password -v /srv/teedy/import:/import sismics/docs-importer:v1.9```

**Comment by Cornelicorn** [comment]
Is the behaviour any different if you try with minimal options, i. e.
```
docker run --name teedy-import --rm -e TEEDY_URL='http://x.x.x.x:8088' -e TEEDY_USERNAME=admin -e TEEDY_PASSWORD=password -v /srv/teedy/import:/import sismics/docs-importer:v1.9```
```
?

**Comment by brightdroid** [comment]
Sadly, does not change anything.

**Comment by Cornelicorn** [comment]
Can you give some info on the file, so I can try to reproduce this? E.g. the file format and the filename.
Is it only this one file or does it also happen for other files?
Does it work with other files at all?
You can add this file to a document to a document in the webinterface without a problem?

**Comment by bigcookie** [comment]
I have a similar issue. tried today. Probably whitespaces is an issue?
This is the error message I get: 
`Upload failed for import/2020513 Fachbuch Whats your problem.pdf: null`

It is a scanned PDF. Scan done by a Brother MFC device. The same document I can upload via web interface of Teedy properly. Not sure if this helps.

I just came across the same thing, while trying to set everything up and giving Teedy a try :-).

**Comment by Cornelicorn** [comment]
> This is the error message I get:
> `Upload failed for import/2020513 Fachbuch Whats your problem.pdf: null`

The error should not be in the filename, at least I don't get an error when importing a PDF with that filename.

> Not sure if this helps.

Definitely, any information is helpful, especially because this now seems to be a broader issue when it's not only happening for @brightdroid.

For completeness' sake, here's the command I use:
```
docker run -d \
    --name='teedy-importer' \
    -e 'TEEDY_URL'='http://192.168.36.86:8080' \
    -e 'TEEDY_USERNAME'='import' \
    -e 'TEEDY_PASSWORD'='password' \
    -e 'TEEDY_LANG'='deu' \
    -e 'TEEDY_ADDTAGS'='true' \
    -e 'TEEDY_COPYFOLDER'='/copy/' \
    -v '/mnt/scanned/':'/import':'rw' \
    -v '/mnt/copy':'/copy':'rw' \
    --restart=unless-stopped \
    sismics/docs-importer:v1.9
```

If you find any file that contains no sensitive information and fails to import, please let me know!

**Comment by bigcookie** [comment]
[2020513 Fachbuch Whats your problem.pdf](https://github.com/sismics/docs/files/6721300/2020513.Fachbuch.Whats.your.problem.pdf)

Attached the file in question. It contains my address, but well. It would be nice, if you can delete the attachment after downloading it.

I cannot tell if I made another mistake. I am using a QNAP TS-653B 6-bay NAS with docker, running a few containers. So I simply added your docker hub file and did the following:
- NAT - port mapping 8080 to 8000 (8000 on host)
- I added the following environment variables
'TEEDY_URL'='http://192.168.20.201:8000'
'TEEDY_USERNAME'='USERNAME'
'TEEDY_PASSWORD'='PASSWORD'
'TEEDY_LANG'='deu'
'TEEDY_ADDTAGS'='false'
'TEEDY_COPYFOLDER'=''
volumes mounted:
'/share/ecoDMS-input':'/import':'rw'
'/share/Container/Teddy-Importer/':'/root/.config/preferences':'rw'

I put the info in the UI and not commandline, but I checked during start the commandline and all seems fine. config-file is being used.

**Comment by Cornelicorn** [comment]
I cannot delete an attachment, but you can delete it now

**Comment by Cornelicorn** [comment]
> * NAT - port mapping 8080 to 8000 (8000 on host)

What do you mean by this? You do not need any port mapping for the import container, or is this for the Teedy container?

> * I added the following environment variables
>   'TEEDY_URL'='http://192.168.20.201:8000'
>   'TEEDY_USERNAME'='USERNAME'
>   'TEEDY_PASSWORD'='PASSWORD'
>   'TEEDY_LANG'='deu'
>   'TEEDY_ADDTAGS'='false'
>   'TEEDY_COPYFOLDER'=''
>   volumes mounted:
>   '/share/ecoDMS-input':'/import':'rw'
>   '/share/Container/Teddy-Importer/':'/root/.config/preferences':'rw'
> 
> I put the info in the UI and not commandline, but I checked during start the commandline and all seems fine. config-file is being used.

This all seems fine, configuration wise. I tried the same options and the document got imported without a problem (also with spaces in the filename).

**Comment by bigcookie** [comment]
Sorry: port mapping for teedy container, not importer

**Comment by bigcookie** [comment]
It seems to be then an issue with my setup on the QNAP... Is there anything I can check inside the container? At the moment both container (importer and teedy) are running completely separate from each other (no docker network). Will try again during the next days...

**Comment by brightdroid** [comment]
Sorry for my late reply.
It doesn't matter which pdf-file I use, you can try this: https://www.ifross.org/Druckfassung/Die_GPL_kommentiert_und_erklaert.pdf

Upload via web-ui works, but cli via ` docker run` does not. Even worse, I tried it again and now the import container just exit with 0 after he outputs the config and didn't even create a new dokument.

Import command:
```bash
read -s pw && docker run --name teedy-import --network host --rm -e TEEDY_URL='http://x.x.x.x:8088' -e TEEDY_USERNAME=admin -e TEEDY_PASSWORD=$pw -v /srv/teedy/import:/import sismics/docs-importer:v1.9
```
This prints following and do not create anything:
> Environment variables replaced
> Teedy Importer 1.9, https://teedy.io
> 
> This program let you import files from your system to Teedy
> 
> Starting in quiet mode with the following configuration:
> Base URL: http://x.x.x.x:8088
> Username: admin
> Password: ***********
> Tag: 
> Add tags given #: false
> Language: eng
> Daemon mode: true
> Copy folder: 
> File filter: *
> 
> Polling the input folder for new files...

**Comment by brightdroid** [comment]
Starting with a pref file didn't change anything:
```bash
docker run --name teedy-import --network host --rm -v $PWD/etc/:/root/ -v /srv/teedy/import:/import sismics/docs-importer:v1.9
```
No document/file created.

**Comment by Cornelicorn** [comment]
Just set up a new blank teedy instance on `v1.9` and could import `Die_GPL_kommentiert_und_erklaert.pdf` with
```
docker run --name teedy-import --network host --rm -e TEEDY_URL='http://192.168.36.87:8080' -e TEEDY_USERNAME=admin -e TEEDY_PASSWORD=admin -v $PWD:/import sismics/docs-importer:v1.9
```
I also retried it multiple times without a problem.

> Upload via web-ui works, but cli via docker run does not. Even worse, I tried it again and now the import container just exit with 0 after he outputs the config and didn't even create a new dokument.

The importer does not have any output except the config and `Polling the input folder for new files...`. It's strange that it exited and even more that it exits successfully without any further output.

Does another machine of yours show the same behavior? This is running on Linux on the same host as teedy for you? 
I have no idea what might be the problem, since the container can contact the instance successfully, otherwise it would fail earlier. This could be some file permission issue, but docker shouldn't care about that.

**Comment by brightdroid** [comment]
This is the docker-compose I use:
```yaml
version: '3.4'

services:
  app:
    image: sismics/docs:v1.9
    restart: unless-stopped
    networks:
      - proxy
      - backend
    environment:
      DOCS_BASE_URL: "https://teedy.example.com"
      DOCS_ADMIN_EMAIL_INIT: "me@example.com"
      DATABASE_URL: "jdbc:postgresql://db:5432/${DB_NAME}"
      DATABASE_USER: "${DB_USER}"
      DATABASE_PASSWORD: "${DB_PASS}"
      DOCS_SMTP_HOSTNAME: "${SMTP_HOST}"
    volumes:
      - /srv/teedy/app:/data
    depends_on:
      - db
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.teedy.entrypoints=https"
        - "traefik.http.routers.teedy.tls=true"
        - "traefik.http.routers.teedy.rule=Host(`teedy.example.com`)"
        - "traefik.http.services.teedy.loadbalancer.server.port=8080"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.master==server"

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - /srv/teedy/db:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.master==server"

  import:
    image: sismics/docs-importer:v1.9
    restart: unless-stopped
    networks:
      - backend
    environment:
      TEEDY_ADDTAGS: "false"
      TEEDY_LANG: "deu"
      TEEDY_URL: "http://app:8080"
      TEEDY_USERNAME: "${IMPORT_USER}"
      TEEDY_PASSWORD: "${IMPORT_PASS}"
    volumes:
      - /srv/teedy/import:/import
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.master==server"

networks:
  proxy:
    external: true
  backend:
```
PS: for import via `docker run` you'll need to add "ports" to the app service.
