### ISSUE TITLE
env variable `DOCS_BASE_URL` doesn't seem to affect assets

### ISSUE THREAD

**Issue by alexanderadam** [sismics/docs#628]
I'm using Teedy behind reverse proxy `jwilder/nginx-proxy`.
Now what is special, is that I'm not using Teedy on a certain subdomain but a certain _path_ (see [`VIRTUAL_PATH`](https://github.com/nginx-proxy/nginx-proxy#path-based-routing)).

Therefore my Teedy compose configuration looks like this:

```yml
version: '3.8'

services:
  teedy-server:
    image: "sismics/docs:v1.10"
    environment:
      DOCS_BASE_URL: "http://foo.bar.com/teedy"
      DATABASE_URL: 'jdbc:postgresql://teedy-db:5432/teedy'
      DATABASE_USER: 'teedy_db_user'
      DATABASE_PASSWORD: 'teedy_db_password'
      VIRTUAL_HOST: "foo.bar.com"
      VIRTUAL_PATH: "/teedy"
      VIRTUAL_PORT: "8080"
      VIRTUAL_DEST: '/'
```

And according to the Teedy Readme generated url's will be using `DOCS_BASE_URL` as base, which makes sense but it doesn't seem to work.

When I visit `http://foo.bar.com/teedy` all further requests are going to `http://foo.bar.com` instead of `http://foo.bar.com/teedy` (i.e `http://foo.bar.com/style/style.min.css`, `http://foo.bar.com/api/theme/stylesheet`, `http://foo.bar.com/docs.min.js`, `http://foo.bar.com/api/theme/image/logo`) and therefore the page is rendered in a broken state:

![Screenshot of Teedy without styles](https://user-images.githubusercontent.com/372620/160366676-e7ecdb26-d597-4137-bffb-d719e73e30d4.png)
 
**PS:** Will you reopen #621 and #622 at a certain point? 🤔
