### ISSUE TITLE
Password Not Working

### ISSUE THREAD

**Issue by jnanadarshan** [sismics/docs#657]
I installed Teddy on docker using the following compose file, however, none of the username password combinations are working.

Please help.

```
version: '3'
services:
# Teedy Application
  teedy-server:
    image: sismics/docs:v1.10
    restart: unless-stopped
    ports:
      # Map internal port to host
      - 8098:8080
    environment:
      # Base url to be used
      DOCS_BASE_URL: "https://dom.mydomain.com"
      # Set the admin email
      @DOCS_ADMIN_EMAIL_INIT: "hey@mydomain.com"
      # Set the admin password (in this example: "superSecure")
      DOCS_ADMIN_PASSWORD_INIT: "password"

    volumes:
      - /home/drogon/AppData/teedy/data:/data  

```
